### ISSUE TITLE
Week-5 Day-4 Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by tacettinkustu** [PolinaStamenova/Capstone-Latin-dance-page#2]

**Comment by Metsanpeitto** [comment]
The page looks quite similar to the original guidelines provided to you. The little icon on the browser tab looks very good.
Optional, some of the buttons could have some effects. 
The page looks really good. Congratualtions.

**Comment by tacettinkustu** [comment]
I like your codes. They looks very clean and organized. The page looks great. But, there is one point I want to express, it would be better if you use lighter font-colors for your main program icons. Thank you. Have a nice work.

**Comment by alexander16108** [comment]
I suggest you use light font for the icons to make the color blend with the background
